name: ALE Psych Tenna Edition
run-name: TV Time [#${{github.run_number}}]

on:
  push:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build ${{ matrix.platform }}
    permissions: write-all
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    strategy:
      matrix:
        include:
          - platform: Android
            os: ubuntu-latest
            container:
            haxe_setup:
            build_cmd: haxelib run lime build android
            extra_libs:
            pre_build_commands: |
              haxelib run lime config ANDROID_SDK $ANDROID_HOME
              haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
              haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
              haxelib run lime config ANDROID_SETUP true
            artifact_path: export/release/android/bin/app/build/outputs/apk/release/*.apk

    steps:
      - name: Pull the New Commit
        uses: actions/checkout@v4.1.7

      - name: Setup Haxe
        if: ${{ !matrix.haxe_setup }}
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.7

      - name: Custom Haxe Setup
        if: ${{ matrix.haxe_setup }}
        run: ${{ matrix.haxe_setup }}

      - name: Install Main Libraries
        run: |
          haxelib --global git hmm https://github.com/ALE-Psych-Crew/hmm
          haxelib --global run hmm setup
          haxelib --global run hmm install

      - name: Install Extra Libraries
        if: ${{ matrix.extra_libs }}
        run: ${{ matrix.extra_libs }}

      - name: Build hxcpp
        run: |
          cd ./.haxelib/hxcpp/git/tools/hxcpp
          haxe compile.hxml
          cd -

      - name: Pre-Build Commands
        if: ${{ matrix.pre_build_commands }}
        run: ${{ matrix.pre_build_commands }}

      - name: Build for ${{ matrix.platform }}
        run: ${{ matrix.build_cmd }}

      - name: Upload Game
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform }} Build
          path: ${{ matrix.artifact_path }}
          if-no-files-found: error

  buildSwitch:
    name: Build Switch
    permissions: write-all
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest

    steps:
      - name: Pull the New Commit
        uses: actions/checkout@v4.1.7

      - name: Setup Haxe
        run: |
          apt-get update
          apt-get install -y wget git neko libgc-dev

          wget https://github.com/HaxeFoundation/haxe/releases/download/4.3.7/haxe-4.3.7-linux64.tar.gz
          mkdir haxe_temp
          tar -xf haxe-4.3.7-linux64.tar.gz -C haxe_temp
          cp -r haxe_temp/haxe_*/* /usr/local/bin/

          mkdir -p ~/haxelib
          haxelib --always --quiet setup ~/haxelib
          haxelib --global --always --quiet update haxelib
          haxelib --global fixrepo

          haxe --version

      - name: Install Main Libraries
        run: |
          haxelib --global git hmm https://github.com/ALE-Psych-Crew/hmm
          haxelib --global run hmm setup
          haxelib --global run hmm install

      - name: Install Extra Libraries
        run: |
          apt-get update
          apt-get install -y libgl1-mesa-dev libglu1-mesa-dev g++-multilib gcc-multilib libasound2-dev libx11-dev libxext-dev libxi-dev libxrandr-dev libxinerama-dev libpulse-dev libmbedtls-dev libpng-dev libturbojpeg-dev libuv1-dev libvorbis-dev libvulkan-dev

          dkp-pacman -Sy --noconfirm || echo "::warning:: The devkitPro repositories could not be synchronized (possible rate limit). Attempting to install using the existing cache..."

          dkp-pacman -S --needed --noconfirm \
            switch-bzip2 switch-cmake switch-curl switch-flac \
            switch-freetype switch-glad switch-glm switch-harfbuzz \
            switch-libdrm_nouveau switch-libjpeg-turbo switch-libmodplug \
            switch-libogg switch-libopus switch-libpng switch-libvorbis \
            switch-libvorbisidec switch-libwebp switch-mesa switch-mpg123 \
            switch-openal-soft switch-opusfile switch-pkg-config switch-sdl2 \
            switch-sdl2_gfx switch-sdl2_image switch-sdl2_mixer \
            switch-sdl2_net switch-sdl2_ttf switch-tools switch-zlib \
            switch-liblua51

      - name: Pre-Build Commands
        run: |
          haxelib remove lime
          haxelib remove hxcpp

          haxelib --always --quiet install format
          haxelib --always --quiet install hxp
          haxelib --always --quiet git hxcpp https://github.com/Slushi-Github/hxcpp-nx.git

          cd ./.haxelib/hxcpp/git/tools/hxcpp
          haxe compile.hxml
          cd -

          haxelib --always --quiet git lime https://github.com/Slushi-Github/lime-nx.git lime-9778682
          haxelib --always --quiet git flixel-switch https://github.com/Slushi-Github/flixel-switch.git
          haxelib --always --quiet git hx_libnx https://github.com/Slushi-Github/hx_libnx.git
          haxelib list

          haxelib run lime rebuild switch

      - name: Build for Switch
        run: |
          haxelib run lime build switch --app-version="4.0.0-${{ github.run_id}}"

      - name: Verify Build Success
        run: |
          if ! ls export/release/switch/bin/*.nro 1> /dev/null 2>&1; then
            echo "::error::.nro file not found."
            exit 1
          fi

      - name: Upload Game
        uses: actions/upload-artifact@v4
        with:
          name: Switch Build
          path: export/release/switch/bin/*.nro
          if-no-files-found: error
